##Pulling the data from mysql workbench

In [1]:
import pandas as pd
import numpy as np
import mysql.connector
from sqlalchemy import create_engine
import urllib.parse

# This safely handles the '@' in your password
password = urllib.parse.quote_plus("Akromah123@")
db_name = "customer_signup" # Make sure this matches your MySQL Schema name!

engine = create_engine(f'mysql+mysqlconnector://root:{password}@localhost/{db_name}')

# Try pulling the data again
try:
    df_customers = pd.read_sql("SELECT * FROM raw_customer_signups", engine)
    df_tickets = pd.read_sql("SELECT * FROM raw_support_tickets", engine)
    print("Success! Data is now in Python.")
except Exception as e:
    print(f"Still hitting a wall: {e}")

Success! Data is now in Python.

#Printing out individaul tables

In [2]:
print(f"This is the customer table: \n", df_customers.head(10))
print(f"This is the ticket table: \n", df_tickets.head(10))

This is the customer table:
   customer_id             name                 email signup_date     source  \
0   CUST00000    Joshua Bryant                                    Instagram
1   CUST00001   Nicole Stewart   nicole1@example.com    02-01-24   LinkedIn
2   CUST00002     Rachel Allen   rachel2@example.com    03-01-24     Google
3   CUST00003  Zachary Sanchez  zachary3@mailhub.org    04-01-24    YouTube
4   CUST00004                   matthew4@mailhub.org    05-01-24   LinkedIn
5   CUST00005    John Gonzales     john5@mailhub.org    06-01-24   Facebook
6   CUST00006    Crystal Mason  crystal6@mailhub.org    07-01-24    YouTube
7   CUST00007   Michael Bailey  michael7@mailhub.org    08-01-24    YouTube
8   CUST00008    Bianca Morris   bianca8@example.com    09-01-24   Referral
9   CUST00009   Cindy Anderson                          10-01-24     Google

    region plan_selected marketing_opt_in  age      gender
0                  basic               No   34      Female
1     West         basic              Yes   29        Male
2    North       PREMIUM              Yes   34  Non-Binary
3                    Pro               No   40        Male
4     West       Premium               No   25       Other
5    South       Premium               No   34       Other
6    North   UnknownPlan              Yes   40        male
7  Central           Pro              Yes   60       Other
8     West           Pro              Yes   25        male
9     East       PREMIUM               No   29      FEMALE
This is the ticket table:
    ticket_id customer_id ticket_date       issue_type resolved
0  TKT0000-1   CUST00203  2024-08-17          Billing      Yes
1  TKT0000-2   CUST00203  2024-07-22  Technical Error      Yes
2  TKT0000-3   CUST00203  2024-07-22            Other      Yes
3  TKT0001-1   CUST00266  2024-09-26    Account Setup      Yes
4  TKT0001-2   CUST00266  2024-10-09  Technical Error       No
5  TKT0001-3   CUST00266  2024-10-21            Other       No
6  TKT0002-1   CUST00152  2024-01-10            Other      Yes
7  TKT0003-1   CUST00009  2024-10-03  Technical Error       No
8  TKT0004-1   CUST00233  2024-09-18            Other      Yes
9  TKT0004-2   CUST00233  2024-08-21    Account Setup      Yes

### Data cleaning

In [3]:
print(f" The shape of the table : \n", df_customers.shape)          # rows, columns
print(f"Columns data type : \n",df_customers.dtypes)         # data types
print(f" Missing value per column : \n", df_customers.isnull().sum()) # missing per column
print(f" Percentage of missing values :\n",df_customers.isnull().mean() * 100)  # % missing
print(f"The description for the customer table :\n  {df_customers.describe()}")

 The shape of the table :
 (281, 10)
Columns data type :
 customer_id           str
name                  str
email                 str
signup_date           str
source                str
region                str
plan_selected         str
marketing_opt_in      str
age                 int64
gender                str
dtype: object
 Missing value per column :
 customer_id         0
name                0
email               0
signup_date         0
source              0
region              0
plan_selected       0
marketing_opt_in    0
age                 0
gender              0
dtype: int64
 Percentage of missing values :
 customer_id         0.0
name                0.0
email               0.0
signup_date         0.0
source              0.0
region              0.0
plan_selected       0.0
marketing_opt_in    0.0
age                 0.0
gender              0.0
dtype: float64
The description for the customer table :
                age
count  281.000000
mean    36.135231
std     14.986048
min     21.000000
25%     25.000000
50%     34.000000
75%     40.000000
max    206.000000

In [4]:
print(f" The shape of the table : \n", df_tickets.shape)          # rows, columns
print(f"Columns data type : \n",df_tickets.dtypes)         # data types
print(f" Missing value per column : \n", df_tickets.isnull().sum()) # missing per column
print(f" The percentage of missing values :\n",df_tickets.isnull().mean() * 100)  # % missing
print(f"The description for the customer table: \n ",df_tickets['ticket_date'])

 The shape of the table :
 (123, 5)
Columns data type :
 ticket_id      str
customer_id    str
ticket_date    str
issue_type     str
resolved       str
dtype: object
 Missing value per column :
 ticket_id      0
customer_id    0
ticket_date    0
issue_type     0
resolved       0
dtype: int64
 The percentage of missing values :
 ticket_id      0.0
customer_id    0.0
ticket_date    0.0
issue_type     0.0
resolved       0.0
dtype: float64
The description for the customer table:
  0      2024-08-17
1      2024-07-22
2      2024-07-22
3      2024-09-26
4      2024-10-09
          ...
118    2024-02-11
119    2024-12-02
120    2024-11-28
121    2024-11-18
122    2024-02-24
Name: ticket_date, Length: 123, dtype: str

In [5]:
q2 = (
    df_customers.groupby("region", dropna=False)
    .apply(lambda g: pd.Series({
        "customers":     len(g),
        "missing_email": g["email"].isna().sum(),
        "missing_age":   g["age"].isna().sum(),
        "missing_opt_in":g["marketing_opt_in"].isna().sum(),
        "missing_plan":  g["plan_selected"].isna().sum(),
    }))
    .reset_index()
)

q2["total_missing"] = q2[["missing_email", "missing_age",
                           "missing_opt_in", "missing_plan"]].sum(axis=1)

# Missing % = total missing fields / (customers × 4 fields) × 100
q2["missing_pct"] = (
    q2["total_missing"] / (q2["customers"] * 4) * 100
).round(1)

print(q2.sort_values("missing_pct", ascending=False).to_string(index=False))
print(f"\nRows with NO region recorded: {df_customers['region'].isna().sum()}")

 region  customers  missing_email  missing_age  missing_opt_in  missing_plan  total_missing  missing_pct
                28              0            0               0             0              0          0.0
Central         36              0            0               0             0              0          0.0
   East         55              0            0               0             0              0          0.0
  North         62              0            0               0             0              0          0.0
  South         57              0            0               0             0              0          0.0
   West         43              0            0               0             0              0          0.0

Rows with NO region recorded: 0

# # Handle missing values and duplicate using the customer_id

In [6]:
# This creates a dataframe of ONLY the rows that are duplicates
duplicates = df_customers[df_customers.duplicated(subset=['customer_id'], keep=False)]

# Sort them so you can see the repeating IDs side-by-side
print(duplicates.sort_values(by='customer_id'))
# Dropping customer_id with id number Other
# Before
print("Before:", len(df_customers))

df_customers = df_customers[df_customers['customer_id']!='Other']

# After
print("After:", len(df_customers))

# Double check 'Other' is completely gone
print("Remaining 'other' rows:", 
      df_customers[df_customers['customer_id'].str.lower().str.strip() == 'other'].shape[0])


print(f"dropping duplicate values using the customer id :\n", df_customers.drop_duplicates(subset=['customer_id']))
print(f"dropna values using the customer id :\n", df_customers.dropna(subset=['customer_id']))

    customer_id             name                    email signup_date  \
147                Robert Carter     robert61@example.com    10-06-24
269              Antonio Hammond  antonio87@inboxmail.net    14-10-24

        source region plan_selected marketing_opt_in  age  gender
147   LinkedIn  South           Pro              Yes   34    Male
269  Instagram   West          prem              Yes   25  FEMALE
Before: 281
After: 281
Remaining 'other' rows: 0
dropping duplicate values using the customer id :
     customer_id                name                  email signup_date  \
0     CUST00000       Joshua Bryant
1     CUST00001      Nicole Stewart    nicole1@example.com    02-01-24
2     CUST00002        Rachel Allen    rachel2@example.com    03-01-24
3     CUST00003     Zachary Sanchez   zachary3@mailhub.org    04-01-24
4     CUST00004                       matthew4@mailhub.org    05-01-24
..          ...                 ...                    ...         ...
276   CUST00295          Gary Smith     gary95@example.com    22-10-24
277   CUST00296     Anthony Roberts  anthony96@mailhub.org    23-10-24
278   CUST00297  Timothy Mclaughlin                           24-10-24
279   CUST00298     Justin Mcintyre   justin98@mailhub.org    25-10-24
280   CUST00299   Mr. Bruce Bridges      mr.99@example.com    26-10-24

        source   region plan_selected marketing_opt_in  age      gender
0    Instagram                  basic               No   34      Female
1     LinkedIn     West         basic              Yes   29        Male
2       Google    North       PREMIUM              Yes   34  Non-Binary
3      YouTube                    Pro               No   40        Male
4     LinkedIn     West       Premium               No   25       Other
..         ...      ...           ...              ...  ...         ...
276     Google     West       PREMIUM              Yes   40
277     Google  Central         Basic              Yes   25      Female
278  Instagram     West         Basic              Yes   60
279    YouTube    South       Premium               No   53        male
280               North       Premium              Yes   29        Male

[280 rows x 10 columns]
dropna values using the customer id :
     customer_id                name                  email signup_date  \
0     CUST00000       Joshua Bryant
1     CUST00001      Nicole Stewart    nicole1@example.com    02-01-24
2     CUST00002        Rachel Allen    rachel2@example.com    03-01-24
3     CUST00003     Zachary Sanchez   zachary3@mailhub.org    04-01-24
4     CUST00004                       matthew4@mailhub.org    05-01-24
..          ...                 ...                    ...         ...
276   CUST00295          Gary Smith     gary95@example.com    22-10-24
277   CUST00296     Anthony Roberts  anthony96@mailhub.org    23-10-24
278   CUST00297  Timothy Mclaughlin                           24-10-24
279   CUST00298     Justin Mcintyre   justin98@mailhub.org    25-10-24
280   CUST00299   Mr. Bruce Bridges      mr.99@example.com    26-10-24

        source   region plan_selected marketing_opt_in  age      gender
0    Instagram                  basic               No   34      Female
1     LinkedIn     West         basic              Yes   29        Male
2       Google    North       PREMIUM              Yes   34  Non-Binary
3      YouTube                    Pro               No   40        Male
4     LinkedIn     West       Premium               No   25       Other
..         ...      ...           ...              ...  ...         ...
276     Google     West       PREMIUM              Yes   40
277     Google  Central         Basic              Yes   25      Female
278  Instagram     West         Basic              Yes   60
279    YouTube    South       Premium               No   53        male
280               North       Premium              Yes   29        Male

[281 rows x 10 columns]

## ── Step 6: Handle missing values

In [7]:

df_customers['region']= df_customers['region'].fillna('Unknown')
df_customers['age'] = pd.to_numeric(df_customers['age'], errors='coerce')
df_customers['age']= df_customers['age'].fillna(df_customers['age'].median())
df_customers['email'] = df_customers['email'].fillna('missing@unknown.com')

In [8]:
print(df_customers[df_customers['signup_date'].isnull()]['region'].value_counts())
# 1. Drop the rows with missing signup dates
df_clean = df_customers.dropna(subset=['signup_date']).copy()

# 2. Verify they are gone
print(f"Rows after dropping missing dates: {len(df_clean)}")

Series([], Name: count, dtype: int64)
Rows after dropping missing dates: 281

# Convert signup_date to datetime

In [9]:
df_customers['signup_date']=pd.to_datetime(df_customers['signup_date'], errors='coerce')
df_tickets['ticket_date']=pd.to_datetime(df_tickets['ticket_date'],  errors='coerce')
# replacing Nan with the median
df_customers['signup_date'] = df_customers['signup_date'].fillna(df_customers['signup_date'].median())
# signup month
df_customers['signup_month']=df_customers['signup_date'].dt.to_period('M')
# signup week
df_customers['signup_week']=df_customers['signup_date'].dt.to_period('W')
print(df_customers['signup_date'].unique().value_counts(),'Nan')

2024-06-14    1
2024-02-01    1
2024-03-01    1
2024-04-01    1
2024-05-01    1
             ..
2024-10-22    1
2024-10-23    1
2024-10-24    1
2024-10-25    1
2024-10-26    1
Name: count, Length: 274, dtype: int64 Nan

C:\Users\augustinecudjoe\AppData\Local\Temp\ipykernel_5480\4122950879.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_customers['signup_date']=pd.to_datetime(df_customers['signup_date'], errors='coerce')

#Standardise inconsistent text values

In [10]:

df_customers['plan_selected']=df_customers['plan_selected'].replace({
        'Pro': 'Professional',
        'PRO': 'Professional',
        'Prem': 'Premium',
        'PREMIUM':'Premium',
        'prem':'Premium',
        'Basic': 'Basic',                    
        'basic':'Basic',
        'Unknownplan': 'Other',
        'Other': 'Other',
        'UnknownPlan':'Other'

    })


cols_to_fix = ['gender', 'source', 'region', 'marketing_opt_in']
for col in cols_to_fix:
    df_customers[col] = df_customers[col].astype(str).str.strip().str.title()

# 2. Master Mapping: Only define the "special cases"
master_map = {
    'gender': { 
        '123': 'Other', 
        'Nan': 'Other', 
        'None': 'Other',
        '': 'Other'
    },
    'Source':{'':'Other',
              '??': 'Other',
              'None':'Other',
              'Nan':'Other'},
    'region':{'':'Other'},
    'marketing_opt_in': {
        'Nil': 'No',
        'None': 'No',
        '123': 'No',
        'Nan': 'No',
        '': 'No'
    }
}

# . Apply everything in one go
df_customers = df_customers.replace(master_map)

# 4 Final touch: Handle any remaining empty strings or "Nan" strings
df_customers = df_customers.replace(['Nan', '', 'None', '??'], 'Other')

print("Data Standardised!")
df_customers_clean=df_customers.copy()

Data Standardised!

In [11]:
df_customers.groupby(['gender'])['customer_id'].size()

gender
Female        89
Male          84
Non-Binary    41
Other         67
Name: customer_id, dtype: int64

# 3. Summary Outputs (Using Pandas Aggregations)

In [12]:
df_customers.groupby('source')['customer_id'].count()

source
Facebook     38
Google       49
Instagram    42
Linkedin     38
Other        14
Referral     43
Youtube      57
Name: customer_id, dtype: int64

# Sign-ups per week (grouped by signup_date)

In [13]:
signup_week=df_customers_clean.groupby('signup_week')['customer_id'].count().reset_index().sort_values(by='customer_id',ascending=False)
print(f" Sign up per week :\n",signup_week)

 Sign up per week :
               signup_week  customer_id
23  2024-06-10/2024-06-16           11
4   2024-01-29/2024-02-04            8
13  2024-04-01/2024-04-07            7
2   2024-01-15/2024-01-21            7
24  2024-06-17/2024-06-23            7
37  2024-09-16/2024-09-22            7
44  2024-11-04/2024-11-10            7
9   2024-03-04/2024-03-10            7
38  2024-09-23/2024-09-29            7
25  2024-06-24/2024-06-30            7
30  2024-07-29/2024-08-04            7
29  2024-07-22/2024-07-28            7
19  2024-05-13/2024-05-19            7
21  2024-05-27/2024-06-02            7
46  2024-12-02/2024-12-08            7
7   2024-02-19/2024-02-25            6
41  2024-10-14/2024-10-20            6
42  2024-10-21/2024-10-27            6
33  2024-08-19/2024-08-25            6
26  2024-07-01/2024-07-07            6
39  2024-09-30/2024-10-06            6
35  2024-09-02/2024-09-08            6
34  2024-08-26/2024-09-01            6
11  2024-03-18/2024-03-24            6
0   2024-01-01/2024-01-07            6
6   2024-02-12/2024-02-18            6
15  2024-04-15/2024-04-21            6
20  2024-05-20/2024-05-26            6
28  2024-07-15/2024-07-21            6
22  2024-06-03/2024-06-09            6
17  2024-04-29/2024-05-05            6
16  2024-04-22/2024-04-28            6
40  2024-10-07/2024-10-13            5
14  2024-04-08/2024-04-14            5
8   2024-02-26/2024-03-03            5
12  2024-03-25/2024-03-31            5
3   2024-01-22/2024-01-28            5
1   2024-01-08/2024-01-14            5
5   2024-02-05/2024-02-11            5
27  2024-07-08/2024-07-14            5
36  2024-09-09/2024-09-15            5
31  2024-08-05/2024-08-11            5
32  2024-08-12/2024-08-18            5
10  2024-03-11/2024-03-17            4
18  2024-05-06/2024-05-12            4
43  2024-10-28/2024-11-03            3
47  2024-12-09/2024-12-15            2
45  2024-11-25/2024-12-01            1

# Sign-ups by source, region, and plan_selected

In [14]:
print(df_customers_clean.groupby('source')['customer_id'].count())

source
Facebook     38
Google       49
Instagram    42
Linkedin     38
Other        14
Referral     43
Youtube      57
Name: customer_id, dtype: int64

In [15]:
print(df_customers_clean.groupby('region')['customer_id'].count())

region
Central    36
East       55
North      62
Other      28
South      57
West       43
Name: customer_id, dtype: int64

In [16]:
print(df_customers_clean.groupby('plan_selected')['customer_id'].size())

plan_selected
Basic           82
Other           14
Premium         96
Professional    89
Name: customer_id, dtype: int64

# Marketing opt-in counts by gender

In [17]:
print(df_customers_clean.groupby('marketing_opt_in')['gender'].value_counts())

marketing_opt_in  gender
No                Male          49
                  Female        47
                  Other         39
                  Non-Binary    23
Yes               Female        42
                  Male          35
                  Other         28
                  Non-Binary    18
Name: count, dtype: int64

#  Age summary: min, max, mean, median, null count

In [18]:
#206 is not real age. drop it
df_customers_clean['age']=df_customers_clean['age'].where(df_customers_clean['age'].between(1,100))

print(f" Age summary  : \n",df_customers_clean['age'].agg(['min','max','mean','median', lambda x: x.isnull().sum()]))
# creating age group
df_customers_clean['age_group']=pd.cut(df_customers_clean['age'],
                                 bins=[0,25,35,45,55,100],
    labels=['18-25','26-35','36-45','46-55','55+'])
print(f"The age group : \n {df_customers_clean['age_group']}")

 Age summary  :
 min         21.000000
max         60.000000
mean        35.528571
median      34.000000
<lambda>     1.000000
Name: age, dtype: float64
The age group :
 0      26-35
1      26-35
2      26-35
3      36-45
4      18-25
       ...
276    36-45
277    18-25
278      55+
279    46-55
280    26-35
Name: age_group, Length: 281, dtype: category
Categories (5, str): ['18-25' < '26-35' < '36-45' < '46-55' < '55+']

# creating the summary table from the customer table

In [19]:
# Drop name, email, age, signup_date
summary_df=df_customers_clean.copy()
print(summary_df.drop(columns=['name','email','age','signup_date']))

    customer_id     source   region plan_selected marketing_opt_in  \
0     CUST00000  Instagram    Other         Basic               No
1     CUST00001   Linkedin     West         Basic              Yes
2     CUST00002     Google    North       Premium              Yes
3     CUST00003    Youtube    Other  Professional               No
4     CUST00004   Linkedin     West       Premium               No
..          ...        ...      ...           ...              ...
276   CUST00295     Google     West       Premium              Yes
277   CUST00296     Google  Central         Basic              Yes
278   CUST00297  Instagram     West         Basic              Yes
279   CUST00298    Youtube    South       Premium               No
280   CUST00299      Other    North       Premium              Yes

         gender signup_month            signup_week age_group
0        Female      2024-06  2024-06-10/2024-06-16     26-35
1          Male      2024-02  2024-01-29/2024-02-04     26-35
2    Non-Binary      2024-03  2024-02-26/2024-03-03     26-35
3          Male      2024-04  2024-04-01/2024-04-07     36-45
4         Other      2024-05  2024-04-29/2024-05-05     18-25
..          ...          ...                    ...       ...
276       Other      2024-10  2024-10-21/2024-10-27     36-45
277      Female      2024-10  2024-10-21/2024-10-27     18-25
278       Other      2024-10  2024-10-21/2024-10-27       55+
279        Male      2024-10  2024-10-21/2024-10-27     46-55
280        Male      2024-10  2024-10-21/2024-10-27     26-35

[281 rows x 9 columns]

# Answer These Business Questions

# Which acquisition source brought in the most users last month?

In [20]:
# find the previous month
last_month = summary_df['signup_date'].dt.to_period('M').max() - 1
print(last_month)

2024-11

In [21]:

# Step 2 — filter to that month
september_data = summary_df[summary_df['signup_date'].dt.to_period('M') == last_month]


top_source = september_data['source'].value_counts().head(5)
print(f"Last month ({last_month}):")
print(f"Top sources for last Month: \n",top_source)

Last month (2024-11):
Top sources for last Month:
 source
Google       3
Instagram    2
Other        2
Referral     1
Facebook     1
Name: count, dtype: int64

# Which region shows signs of missing or incomplete data?

In [22]:
# checking missing source per region
missing_region=pd.crosstab(summary_df['region'],summary_df['source'])
print(missing_region)

source   Facebook  Google  Instagram  Linkedin  Other  Referral  Youtube
region
Central         6      10          4         3      1         5        7
East           10       7          8         7      1         7       15
North           7      12         14         9      4        10        6
Other           6       5          1         1      2         5        8
South           7       8          7        11      3         8       13
West            2       7          8         7      3         8        8

# 3. Are older users more or less likely to opt in to marketing?

In [23]:
pivot = pd.pivot_table(
    summary_df, 
    index='age_group', 
    columns='marketing_opt_in', 
    aggfunc='size', 
    fill_value=0
)

# Add a calculation to see the 'Yes' percentage (likelihood)
pivot['Opt-in %'] = ((pivot['Yes'] / (pivot['Yes'] + pivot['No'])) * 100).round(2)

print(pivot)

marketing_opt_in  No  Yes  Opt-in %
age_group
18-25             46   31     40.26
26-35             51   39     43.33
36-45             26   24     48.00
46-55             26   23     46.94
55+                8    6     42.86

# 4.Which plan is most commonly selected, and by which age group?

In [24]:

plan_selected=pd.pivot_table(summary_df,index='age_group',columns='plan_selected',aggfunc='size')
print(plan_selected)

plan_selected  Basic  Other  Premium  Professional
age_group
18-25             28      2       23            24
26-35             23      5       31            31
36-45             11      3       23            13
46-55             14      3       15            17
55+                5      1        4             4

# Merging the two tables

In [25]:
merge_df=df_customers_clean.merge(df_tickets, how='inner',on='customer_id',indicator=True)
print(f"Merged tables : \n {merge_df}")

Merged tables :
     customer_id                name                  email signup_date  \
0     CUST00005       John Gonzales      john5@mailhub.org  2024-06-01
1     CUST00007      Michael Bailey   michael7@mailhub.org  2024-08-01
2     CUST00007      Michael Bailey   michael7@mailhub.org  2024-08-01
3     CUST00009      Cindy Anderson                  Other  2024-10-01
4     CUST00017          Patty Paul  patty17@inboxmail.net  2024-01-18
..          ...                 ...                    ...         ...
114   CUST00286    Bethany Campbell  bethany86@mailhub.org  2024-10-13
115   CUST00295          Gary Smith     gary95@example.com  2024-10-22
116   CUST00297  Timothy Mclaughlin                  Other  2024-10-24
117   CUST00297  Timothy Mclaughlin                  Other  2024-10-24
118   CUST00297  Timothy Mclaughlin                  Other  2024-10-24

        source   region plan_selected marketing_opt_in   age      gender  \
0     Facebook    South       Premium               No  34.0       Other
1      Youtube  Central  Professional              Yes  60.0       Other
2      Youtube  Central  Professional              Yes  60.0       Other
3       Google     East       Premium               No  29.0      Female
4      Youtube     East  Professional               No  53.0  Non-Binary
..         ...      ...           ...              ...   ...         ...
114     Google    North       Premium              Yes  21.0        Male
115     Google     West       Premium              Yes  40.0       Other
116  Instagram     West         Basic              Yes  60.0       Other
117  Instagram     West         Basic              Yes  60.0       Other
118  Instagram     West         Basic              Yes  60.0       Other

    signup_month            signup_week age_group  ticket_id ticket_date  \
0        2024-06  2024-05-27/2024-06-02     26-35  TKT0008-1  2024-06-04
1        2024-08  2024-07-29/2024-08-04       55+  TKT0036-1  2024-08-07
2        2024-08  2024-07-29/2024-08-04       55+  TKT0036-2  2024-08-23
3        2024-10  2024-09-30/2024-10-06     26-35  TKT0003-1  2024-10-03
4        2024-01  2024-01-15/2024-01-21     46-55  TKT0030-1  2024-02-03
..           ...                    ...       ...        ...         ...
114      2024-10  2024-10-07/2024-10-13     18-25  TKT0042-3  2024-11-01
115      2024-10  2024-10-21/2024-10-27     36-45  TKT0027-1  2024-11-01
116      2024-10  2024-10-21/2024-10-27       55+  TKT0054-1  2024-11-09
117      2024-10  2024-10-21/2024-10-27       55+  TKT0054-2  2024-11-01
118      2024-10  2024-10-21/2024-10-27       55+  TKT0054-3  2024-11-13

          issue_type resolved _merge
0              Other      Yes   both
1            Billing      Yes   both
2              Other      Yes   both
3    Technical Error       No   both
4              Other      Yes   both
..               ...      ...    ...
114  Technical Error      Yes   both
115            Other      Yes   both
116            Other      Yes   both
117    Account Setup      Yes   both
118  Technical Error      Yes   both

[119 rows x 18 columns]

# We must drop the NaN values from the merged tables

In [26]:
df_merged_clean=merge_df.dropna(subset='customer_id')
print(df_merged_clean)

    customer_id                name                  email signup_date  \
0     CUST00005       John Gonzales      john5@mailhub.org  2024-06-01
1     CUST00007      Michael Bailey   michael7@mailhub.org  2024-08-01
2     CUST00007      Michael Bailey   michael7@mailhub.org  2024-08-01
3     CUST00009      Cindy Anderson                  Other  2024-10-01
4     CUST00017          Patty Paul  patty17@inboxmail.net  2024-01-18
..          ...                 ...                    ...         ...
114   CUST00286    Bethany Campbell  bethany86@mailhub.org  2024-10-13
115   CUST00295          Gary Smith     gary95@example.com  2024-10-22
116   CUST00297  Timothy Mclaughlin                  Other  2024-10-24
117   CUST00297  Timothy Mclaughlin                  Other  2024-10-24
118   CUST00297  Timothy Mclaughlin                  Other  2024-10-24

        source   region plan_selected marketing_opt_in   age      gender  \
0     Facebook    South       Premium               No  34.0       Other
1      Youtube  Central  Professional              Yes  60.0       Other
2      Youtube  Central  Professional              Yes  60.0       Other
3       Google     East       Premium               No  29.0      Female
4      Youtube     East  Professional               No  53.0  Non-Binary
..         ...      ...           ...              ...   ...         ...
114     Google    North       Premium              Yes  21.0        Male
115     Google     West       Premium              Yes  40.0       Other
116  Instagram     West         Basic              Yes  60.0       Other
117  Instagram     West         Basic              Yes  60.0       Other
118  Instagram     West         Basic              Yes  60.0       Other

    signup_month            signup_week age_group  ticket_id ticket_date  \
0        2024-06  2024-05-27/2024-06-02     26-35  TKT0008-1  2024-06-04
1        2024-08  2024-07-29/2024-08-04       55+  TKT0036-1  2024-08-07
2        2024-08  2024-07-29/2024-08-04       55+  TKT0036-2  2024-08-23
3        2024-10  2024-09-30/2024-10-06     26-35  TKT0003-1  2024-10-03
4        2024-01  2024-01-15/2024-01-21     46-55  TKT0030-1  2024-02-03
..           ...                    ...       ...        ...         ...
114      2024-10  2024-10-07/2024-10-13     18-25  TKT0042-3  2024-11-01
115      2024-10  2024-10-21/2024-10-27     36-45  TKT0027-1  2024-11-01
116      2024-10  2024-10-21/2024-10-27       55+  TKT0054-1  2024-11-09
117      2024-10  2024-10-21/2024-10-27       55+  TKT0054-2  2024-11-01
118      2024-10  2024-10-21/2024-10-27       55+  TKT0054-3  2024-11-13

          issue_type resolved _merge
0              Other      Yes   both
1            Billing      Yes   both
2              Other      Yes   both
3    Technical Error       No   both
4              Other      Yes   both
..               ...      ...    ...
114  Technical Error      Yes   both
115            Other      Yes   both
116            Other      Yes   both
117    Account Setup      Yes   both
118  Technical Error      Yes   both

[119 rows x 18 columns]

# (Optional) Which plan’s users are most likely to contact support?

In [27]:
print('Users likely to contact support ......')
pd.pivot_table(df_merged_clean, index='plan_selected',values='customer_id', columns='issue_type',fill_value=0, aggfunc='count', margins=True, margins_name='total')

Users likely to contact support ......

issue_type,Account Setup,Billing,Login Issue,Other,Technical Error,total
plan_selected,,,,,,
Basic,4,9,11,9,5,38
Other,0,1,3,1,3,8
Premium,6,4,6,6,4,26
Professional,7,11,9,11,9,47
total,17,25,29,27,21,119

# Count how many customers contacted support within 2 weeks of sign-up

In [28]:
# calculate the number of days
df_merged_clean['days']=(df_merged_clean['ticket_date']-df_merged_clean['signup_date']).dt.days
df_merged_clean=df_merged_clean[df_merged_clean['days']>=0].copy()

# grouping the days into within and after two weeks
df_merged_clean['days_group'] =pd.cut(df_merged_clean['days'],bins=[-1, 14, np.inf], labels=['within_2weeks','After_2weeks'])


print('total customers within two weeks')
df_merged_clean.groupby('days_group')['customer_id'].count()

total customers within two weeks

days_group
within_2weeks    66
After_2weeks     53
Name: customer_id, dtype: int64

In [29]:
print("Quick stats on days to ticket:")
print(df_merged_clean['days'].describe())

print("\nNumber of NaNs (users with no tickets):")
print(df_merged_clean['days'].isna().sum())

Quick stats on days to ticket:
count    119.000000
mean      13.193277
std        9.156157
min        0.000000
25%        4.000000
50%       14.000000
75%       20.500000
max       29.000000
Name: days, dtype: float64

Number of NaNs (users with no tickets):
0

# Summarise support activity by plan and region (Group by plan and region)

In [30]:
print('..... support activity by region and plan .....')
df_merged_clean.groupby(['plan_selected','region'])['ticket_id'].count()
pd.pivot_table(df_merged_clean, index='region',columns='plan_selected',values='issue_type',aggfunc='count',fill_value=0)

..... support activity by region and plan .....

plan_selected  Basic  Other  Premium  Professional
region
Central            2      0        6            10
East               8      2        1            14
North              3      6        6            11
Other              2      0        0             3
South             14      0        2             3
West               9      0       11             6

In [31]:
df_final=df_customers_clean[df_customers_clean['customer_id']!='Other']
print(df_final['customer_id'].unique())

<StringArray>
['CUST00000', 'CUST00001', 'CUST00002', 'CUST00003', 'CUST00004', 'CUST00005',
 'CUST00006', 'CUST00007', 'CUST00008', 'CUST00009',
 ...
 'CUST00290', 'CUST00291', 'CUST00292', 'CUST00293', 'CUST00294', 'CUST00295',
 'CUST00296', 'CUST00297', 'CUST00298', 'CUST00299']
Length: 279, dtype: str

# Push back the code to the database

In [32]:
# push the clean code back to mysql
# Convert Period columns to string format
df_final['signup_month'] = df_final['signup_month'].astype(str)
df_final['signup_week'] = df_final['signup_week'].astype(str)

df_final.to_sql(
    'customer_clean',   # new clean table name
    engine,
    if_exists='replace',        # replace table each time Python runs
    index=False
)
df_tickets.to_sql(
    'tickets_clean',   # new clean table name
    engine,
    if_exists='replace',        # replace table each time Python runs
    index=False
)
print(f"Written {len(df_final)} clean rows to database")
print(f"Written {len(df_tickets)} clean rows to database")

Written 279 clean rows to database
Written 123 clean rows to database